name: CI

on: [push]

jobs:
  check-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - run: uv run pre-commit run -a
    - run: uv run python -m unittest
